sudo: required

language: go

go:
  - 1.5
  - tip

services:
  - docker

before_install:
  - env | sort
  - cd ./SDKs && curl -LO $OSX_SDK_TARBALL && cd ../
  - docker build -t $TRAVIS_REPO_SLUG .
script:
  - docker info
